auth:
  ftp:
    host: 192.168.0.218
    user: ftpdba
    pass: bobotti
    port: 21
  db:
    host: 192.168.0.218
    user: ubuntu
    pass: Bobotti123!
    port: 3306
#CUDA/CPU
identification:
  identification_workers: 10
  levels: 2
  device: cuda
diarization:
  #base tiny medium large large-v2
  model: tiny
  device: cuda
  dualgpu: False
httpserver:
  ip: 0.0.0.0
  port: 1001
  debug: True
  threads: 2