auth:
  ftp:
    host: 192.168.0.218
    user: ftpdba
    pass: bobotti
    port:
  db:
    host: 192.168.0.218
    user: ubuntu
    pass: Bobotti123!
    port: 20121
#CUDA/CPU
identification:
  identification_workers: 5
  levels: 1
  device: cpu
diarization:
  #base tiny medium large large-v2
  model: medium
  device: cpu
httpserver:
  ip: 0.0.0.0
  port: 50038